name: Checkov Check
on:
  pull_request
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/aws
          quiet: true # optional: display only failed checks
          soft_fail: true
          output_format: sarif
