name: kiks scanner
on:
  pull_request:
jobs:
  kics:
    name: KICS scanner
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run kics Scan
        uses: checkmarx/kics-github-action@v1.2
        with:
          path: 'terraform'
          output_formats: 'sarif'
      - name: Upload SARIF kics file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
